### ISSUE TITLE
As a developer, I want to be able to authenticate a user using stych

### ISSUE THREAD

**Issue by naberken** [uwstout-cs458-s22/advisor002-api#2]

**Comment by naberken** [comment]
1. authorization should fail if there is no authorization header
2. authorization should fail if there is no bearer token
3. authorization should fail if there is a bearer with no token
4. authorization should fail if there is a bad token

**Comment by Eneuwi** [comment]
4. If the user doesn't have an email in the database then pass a new email in
5. authorization should fail if email is invaild
